"""Stage three: the transcript becomes memories, the memories become chapters, both stored.

Two services do the thinking — `semantic_segmentation.memories` divides the transcript,
`semantic_segmentation.chapters` groups what it produced — and this module is what runs them
in order and writes the result down. The writing is the part that did not exist before: both
tables were created with their migrations noting that nothing filled them, and the reads the
video agent is built on had nothing to read.

The order the two writes happen in is forced by the data. A memory points at the chapter it
was grouped into, and a chapter's id is generated by the database rather than known in
advance, so the chapters are written first and their ids come back out of that write. The
mapping from a memory to its chapter is built here, from the memories each chapter already
holds, because this is the only place that has the grouping and the ids at the same time.

Chapter grouping is allowed to fail without costing the memories. The `memories` table is
designed for exactly that state — `chapter_id` is nullable, and every memory passes through
it before grouping runs — so a failure there stores the memories ungrouped and reports it,
rather than discarding a division of the transcript that succeeded.
"""

from __future__ import annotations

import logging
from collections.abc import Sequence
from dataclasses import dataclass, field

from backend.services.semantic_segmentation.chapters import VideoChapters, group_memories
from backend.services.semantic_segmentation.memories import VideoMemories, segment_transcript
from backend.services.transcripts import NormalizedTranscript
from backend.storage.postgres import (
    NewChapter,
    NewMemory,
    PostgresChapters,
    PostgresMemories,
)

from .result import CHAPTER_GROUPING_FAILED, SEGMENTATION_FAILED

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SegmentedVideo:
    """How much of the video's structure this run managed to produce and store."""

    memory_count: int = 0
    chapter_count: int = 0
    problems: tuple[str, ...] = field(default_factory=tuple)


def segment_and_store(
    video_id: str,
    transcript: NormalizedTranscript,
    *,
    pool=None,
) -> SegmentedVideo:
    """Divide `transcript` into memories, group them into chapters, and store both.

    Returns what was stored rather than raising, because everything before this stage is
    already durable: the video is in Blob Storage and its transcript is in the database, and
    a model that would not answer is a reason to report an incomplete video rather than to
    lose a complete download. The exception itself is logged with its traceback, since the
    problem code that comes back says only which stage gave up.
    """
    try:
        memories = segment_transcript(transcript)
    except Exception:
        logger.exception("Dividing video %s into memories failed", video_id)
        return SegmentedVideo(problems=(SEGMENTATION_FAILED,))

    try:
        chapters = group_memories(memories)
    except Exception:
        logger.exception("Grouping video %s into chapters failed", video_id)
        memory_count = _store_memories(video_id, memories, chapters=None, pool=pool)
        return SegmentedVideo(
            memory_count=memory_count, problems=(CHAPTER_GROUPING_FAILED,)
        )

    chapter_ids = PostgresChapters(pool=pool).replace(
        video_id, [_to_new_chapter(chapter, chapters.model) for chapter in chapters]
    )
    memory_count = _store_memories(
        video_id, memories, chapters=chapters, chapter_ids=chapter_ids, pool=pool
    )
    return SegmentedVideo(memory_count=memory_count, chapter_count=len(chapter_ids))


def _store_memories(
    video_id: str,
    memories: VideoMemories,
    *,
    chapters: VideoChapters | None,
    chapter_ids: Sequence[str] = (),
    pool,
) -> int:
    """Write every memory, each pointing at the chapter it was grouped into.

    `chapters` is None when grouping did not run or did not finish, and every memory is then
    written ungrouped.
    """
    chapter_id_by_memory_index = _chapter_ids_by_memory_index(chapters, chapter_ids)
    return PostgresMemories(pool=pool).replace(
        video_id,
        [
            NewMemory(
                memory_index=memory.index,
                text=memory.transcript,
                summary=memory.summary,
                start_seconds=memory.start_seconds,
                end_seconds=memory.end_seconds,
                chapter_id=chapter_id_by_memory_index.get(memory.index),
                model=memories.model,
            )
            for memory in memories
        ],
    )


def _chapter_ids_by_memory_index(
    chapters: VideoChapters | None, chapter_ids: Sequence[str]
) -> dict[int, str]:
    """Which chapter id each memory index belongs to.

    `chapter_ids` comes back from the write in the same order the chapters were handed to
    it, which is `chapter_index` order, so a chapter and its id sit at the same position in
    the two sequences. Each chapter already holds the memories it was grouped from, so the
    mapping is read off the grouping itself rather than recomputed from the time ranges —
    the two would agree, but only one of them is what the model actually decided.
    """
    if chapters is None:
        return {}
    return {
        memory.index: chapter_id
        for chapter, chapter_id in zip(chapters.chapters, chapter_ids)
        for memory in chapter.memories
    }


def _to_new_chapter(chapter, model: str) -> NewChapter:
    """One produced chapter as the row the database is asked to write."""
    return NewChapter(
        chapter_index=chapter.index,
        title=chapter.title,
        summary=chapter.summary,
        start_seconds=chapter.start_seconds,
        end_seconds=chapter.end_seconds,
        model=model,
    )
